### PR TITLE
Sort by filename

### PR DESCRIPTION
**Pull request by jwidness**
added 2 lines to sort by filename instead of zooniverse id

### CODE REVIEW

**Comment by adammcmaster** [comment]
Cool. That'll run this afternoon.

**Comment by jwidness** [comment]
Hm, the identified chimps list doesn't seem to have updated since the change...

**Comment by adammcmaster** [comment]
Yeah, it looks like there's an error int he updated code. I'm going to look into it today.

**Comment by adammcmaster** [comment]
Ah, it looks like the `except!` method is only a Rails thing. I've changed it to use `delete` instead in ac6a99721051c090c94ba8488796ebcb8c520aff.

**Comment by jwidness** [comment]
Sorry about that!  But I think if you go with delete, map! should be replaced with just map.

**Comment by adammcmaster** [comment]
Ah, yes I think you're right. I've updated that now.

**Comment by jwidness** [comment]
Awesome, thanks so much!  I think everything is working now except the moderator tags, any ideas on that?

Edit: actually, I had a thought -- I posted to #13

**Comment by adammcmaster** [comment]
Cool, I'm hoping to look at the tags issue this week.

**Pull request merged**
