### PR TITLE
secondary sort by start time and mod tag change

### PR DESCRIPTION
**Pull request by jwidness**
sort first by file name, then by start time
allow mods to tag with chimp as a substring

### CODE REVIEW

**Comment by adammcmaster** [comment]
Did you also want to change `mod_tags.include?('gorilla')` on line 123 and line 127?

**Comment by jwidness** [comment]
No, the mods don't use any variations on the gorilla tag.  But thanks for checking : )

**Comment by adammcmaster** [comment]
OK, cool.

**Comment by jwidness** [comment]
The list doesn't seem to have updated today.  Hopefully I didn't break it with the changes :/

**Comment by adammcmaster** [comment]
Looks like there are a few syntax errors. I'll take a look later this morning.

**Comment by jwidness** [comment]
Sorry about that!  Thanks for fixing it -- everything looks perfect now, hopefully that's it on the changes for a while!

**Comment by jwidness** [comment]
The list hasn't updated for a couple days, do you think you could check on it?
Thanks!

**Comment by jwidness** [comment]
Still no update, any chance you could take a look?  Thanks!

**Comment by adammcmaster** [comment]
Sorry, I was away for the last couple of weeks. It looks like this has been working for the last few days, can you confirm?

**Comment by jwidness** [comment]
Yep, we're looking good again!  Thanks!

**Pull request merged**
